import fetch from 'node-fetch';
import BinocularsResultInterface from '../interfaces/BinocularsResult';
import getLighthouseScoreColor from './getLighthouseScoreColor';

const getBadge = ({ title, score }: { title: string; score: number }) =>
  `<img src="https://img.shields.io/badge/${title}-${score}-${getLighthouseScoreColor(
    {
      isHex: false,
      score,
    },
  )}?style=flat-square" />`;

export default async ({
  commentAccessToken,
  commentUrl,
  results,
}: {
  commentAccessToken: string;
  commentUrl: string;
  results: BinocularsResultInterface[];
}) => {
  let markdown = '\n<table><tr><th colspan="2">Binoculars Results</th></tr>';

  results.forEach((result) => {
    const badge = getBadge({
      title: 'seo',
      score: result.result.categories.binocularsSeo.score * 100,
    });

    // table header
    markdown += `<tr><td>URL</td><td>${result.url}</td></tr>`;
    markdown += `<tr><td>score</td><td>${badge}</td></tr>`;

    // if we have a URL for the full report
    if (result.report) {
      markdown += `<tr><td>report</td><td>${result.report}</td></tr>`;
    }
  });

  // table end
  markdown += `</table>\n\n`;

  // create an identifier within the comment when searching comments
  // in the future
  const commentIdentifier = '<!-- generated by binoculars -->';
  markdown += commentIdentifier;

  // establish existing comment
  let existingComment;

  // get existing comments to see if we've already posted scores
  const existingCommentsResult = await fetch(commentUrl, {
    method: 'get',
    headers: {
      'content-type': 'application/json',
      authorization: `token ${commentAccessToken}`,
    },
  });
  const existingCommentsJsonResult = await existingCommentsResult.json();

  if (
    Array.isArray(existingCommentsJsonResult) &&
    existingCommentsJsonResult.length
  ) {
    existingComment = existingCommentsJsonResult.find((current) =>
      current.body.includes(commentIdentifier),
    );
  }

  // create or update the comment with scores
  const shouldUpdate = existingComment && existingComment.id;
  const url = !shouldUpdate
    ? commentUrl
    : `${commentUrl}/${existingComment.id}`;

  const result = await fetch(url, {
    method: !shouldUpdate ? 'post' : 'put',
    body: JSON.stringify({
      ...(shouldUpdate
        ? {}
        : {
            event: 'COMMENT',
          }),
      body: markdown,
    }),
    headers: {
      'content-type': 'application/json',
      authorization: `token ${commentAccessToken}`,
    },
  });
  const jsonResult = await result.json();

  if (!jsonResult.id) {
    throw Error(jsonResult.message || 'unknown error');
  }
};
