export default [
  `<p>To be announced properly by assistive technologies,
both
<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Forms" rel="noopener">native HTML controls</a>
and
<a href="https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex" rel="noopener">custom ARIA controls</a>
must have <a href="/labels-and-text-alternatives">accessible names</a>
that convey their purpose.</p>`,
  `<p><code>&lt;label&gt;</code> elements are a common way to assign names to native controls.
If you unintentionally associate multiple labels with a single control,
you'll create inconsistent behavior across browsers and assistive technologies:
some will read the first label, some will read the last label,
and others will read both labels.</p>`,
  `<h2>How the Lighthouse multiple label audit fails <a class="w-headline-link" href="#how-the-lighthouse-multiple-label-audit-fails" aria-hidden="true">#</a></h2>`,
  `<p><a href="https://developers.google.com/web/tools/lighthouse/">Lighthouse</a>
flags form elements that have more than one label:</p>`,
  `<figure>
  <img class="w-screenshot" src="https://webdev.imgix.net/form-field-multiple-labels/form-field-multiple-labels.png" alt="Lighthouse audit showing form elements with multiple labels">
</figure>`,
  `<p>There are several common scenarios that cause this audit to fail:</p>`,
  `<ul>
<li>
<p>Explicitly associating more than one <code>&lt;label&gt;</code> element
with a form element using the <code>for</code> attribute. For example:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label one<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label two<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span></code></pre>
</web-copy-code></li>
<li>
<p>Implicitly associating one <code>&lt;label&gt;</code> element with a form element
and explicitly associating another using the <code>for</code> attribute. For example:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label one<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span><span class="token punctuation">&gt;</span></span>Label two<br>  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span></code></pre>
</web-copy-code></li>
<li>
<p>Associating one <code>&lt;label&gt;</code> element with a form element
and associating another element using the <code>aria-labelledby</code> attribute.
For example:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label one<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1_label<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label two<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token attr-name">aria-labelledby</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1_label<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span></code></pre>
</web-copy-code></li>
<li>
<p>Having nested <code>&lt;label&gt;</code> elements. For example:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span><span class="token punctuation">&gt;</span></span>Label one<br>  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span><span class="token punctuation">&gt;</span></span>Label two<br>    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span><br>  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span></code></pre>
</web-copy-code></li>
</ul>`,
  `<h2>How to remove duplicate form labels <a class="w-headline-link" href="#how-to-remove-duplicate-form-labels" aria-hidden="true">#</a></h2>`,
  `<p>Make sure that each form element on your page has no more than one label.
Labels can be assigned in three ways:</p>`,
  `<ul>
<li>
<p>Implicitly, by making the <code>&lt;label&gt;</code> element a parent of the form element:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span><span class="token punctuation">&gt;</span></span>Label for checkbox<br>  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span></code></pre>
</web-copy-code></li>
<li>
<p>Explicitly, by associating a <code>&lt;label&gt;</code> element with the form element
using the <code>for</code> attribute:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label for checkbox<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span></code></pre>
</web-copy-code></li>
<li>
<p>Using the <code>aria-labelledby</code> attribute to associate the form element
with a separate element using its ID:</p>
<web-copy-code><pre class="language-html"><code class="language-html"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1_label<span class="token punctuation">"</span></span><span class="token punctuation">&gt;</span></span>Label for checkbox<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">&gt;</span></span><br><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox<span class="token punctuation">"</span></span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1<span class="token punctuation">"</span></span> <span class="token attr-name">aria-labelledby</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkbox1_label<span class="token punctuation">"</span></span> <span class="token punctuation">/&gt;</span></span></code></pre>
</web-copy-code></li>
</ul>`,
  `<p>Verify that you're using only one of these techniques for each form element.</p>`,
  `<h2>Resources <a class="w-headline-link" href="#resources" aria-hidden="true">#</a></h2>`,
  `<ul>
<li><a href="https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/accessibility/form-field-multiple-labels.js" rel="noopener">Source code for <strong>Form fields have multiple labels</strong> audit</a></li>
<li><a href="https://dequeuniversity.com/rules/axe/3.3/form-field-multiple-labels" rel="noopener">Form fields do not have duplicate labels (Deque University)</a></li>
<li><a href="https://web.dev/form-field-multiple-labels/" rel="noopener">Form fields have multiple labels</a></li></ul>`,
];
