name: Comment
on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: npm install
    - run: npm run build
    - name: Comment
      run: |
        node ./dist/bin/binoculars.js --enableComments \
        --urls "https://www.foo.software|https://www.foo.software/lighthouse/" \
        --commentAccessToken "${{ secrets.BINOCULARS_GITHUB_ACCESS_TOKEN }}" \
        --commentUrl "https://api.github.com/repos/foo-software/binoculars/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews"
